/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        brand: {
          primary:          'var(--color-brand-primary)',
          'primary-hover':  'var(--color-brand-primary-hover)',
          'primary-subtle': 'var(--color-brand-primary-subtle)',
          'focus-ring':     'var(--color-brand-focus-ring)',
        },
        text: {
          default:   'var(--color-text-default)',
          subtle:    'var(--color-text-subtle)',
          disabled:  'var(--color-text-disabled)',
          inverse:   'var(--color-text-inverse)',
          'on-dark': 'var(--color-text-on-dark)',
          brand:     'var(--color-text-brand)',
          error:     'var(--color-text-error)',
          warning:   'var(--color-text-warning)',
          success:   'var(--color-text-success)',
        },
        bg: {
          default:          'var(--color-bg-default)',
          surface:          'var(--color-bg-surface)',
          'surface-alt':    'var(--color-bg-surface-alt)',
          overlay:          'var(--color-bg-overlay)',
          brand:            'var(--color-bg-brand)',
          disabled:         'var(--color-bg-disabled)',
          error:            'var(--color-bg-error)',
          'error-subtle':   'var(--color-bg-error-subtle)',
          warning:          'var(--color-bg-warning)',
          'warning-subtle': 'var(--color-bg-warning-subtle)',
          success:          'var(--color-bg-success)',
          'success-subtle': 'var(--color-bg-success-subtle)',
        },
        border: {
          default: 'var(--color-border-default)',
          subtle:  'var(--color-border-subtle)',
          strong:  'var(--color-border-strong)',
          brand:   'var(--color-border-brand)',
          error:   'var(--color-border-error)',
          warning: 'var(--color-border-warning)',
          success: 'var(--color-border-success)',
        },
        status: {
          error:            'var(--color-status-error)',
          'error-subtle':   'var(--color-status-error-subtle)',
          warning:          'var(--color-status-warning)',
          'warning-subtle': 'var(--color-status-warning-subtle)',
          success:          'var(--color-status-success)',
          'success-dark':   'var(--color-status-success-dark)',
          'success-subtle': 'var(--color-status-success-subtle)',
        },
        interactive: {
          default:  'var(--color-interactive-default)',
          hover:    'var(--color-interactive-hover)',
          active:   'var(--color-interactive-active)',
          disabled: 'var(--color-interactive-disabled)',
        },
        accent: {
          yellow:          'var(--color-accent-yellow)',
          'yellow-subtle': 'var(--color-accent-yellow-subtle)',
          teal:            'var(--color-accent-teal)',
          'teal-subtle':   'var(--color-accent-teal-subtle)',
          purple:          'var(--color-accent-purple)',
          'purple-subtle': 'var(--color-accent-purple-subtle)',
          pink:            'var(--color-accent-pink)',
          'pink-subtle':   'var(--color-accent-pink-subtle)',
        },
      },
      spacing: {
        '0-5':   'var(--spacing-0-5)',
        'xs':    'var(--spacing-xs)',
        'sm':    'var(--spacing-sm)',
        'sm-md': 'var(--spacing-sm-md)',
        'md':    'var(--spacing-md)',
        'lg':    'var(--spacing-lg)',
        'xl':    'var(--spacing-xl)',
        '2xl':   'var(--spacing-2xl)',
        '3xl':   'var(--spacing-3xl)',
        '4xl':   'var(--spacing-4xl)',
        '5xl':   'var(--spacing-5xl)',
        '6xl':   'var(--spacing-6xl)',
      },
      borderRadius: {
        'xs':   'var(--radius-xs)',
        'sm':   'var(--radius-sm)',
        'md':   'var(--radius-md)',
        'lg':   'var(--radius-lg)',
        'xl':   'var(--radius-xl)',
        'full': 'var(--radius-full)',
      },
      borderWidth: {
        DEFAULT: 'var(--border-width-default)',
        thick:   'var(--border-width-thick)',
        focus:   'var(--border-width-focus)',
      },
      fontSize: {
        'label-sm':    ['var(--type-size-label-sm)',    { lineHeight: 'var(--type-lh-label-sm)' }],
        'label-md':    ['var(--type-size-label-md)',    { lineHeight: 'var(--type-lh-label-md)' }],
        'body-sm':     ['var(--type-size-body-sm)',     { lineHeight: 'var(--type-lh-body-sm)' }],
        'body-md':     ['var(--type-size-body-md)',     { lineHeight: 'var(--type-lh-body-md)' }],
        'title-md':    ['var(--type-size-title-md)',    { lineHeight: 'var(--type-lh-title-md)' }],
        'title-lg':    ['var(--type-size-title-lg)',    { lineHeight: 'var(--type-lh-title-lg)' }],
        'headline-sm': ['var(--type-size-headline-sm)', { lineHeight: 'var(--type-lh-headline-sm)' }],
        'headline-md': ['var(--type-size-headline-md)', { lineHeight: 'var(--type-lh-headline-md)' }],
        'headline-lg': ['var(--type-size-headline-lg)', { lineHeight: 'var(--type-lh-headline-lg)' }],
        'display-sm':  ['var(--type-size-display-sm)',  { lineHeight: 'var(--type-lh-display-sm)' }],
        'display-md':  ['var(--type-size-display-md)',  { lineHeight: 'var(--type-lh-display-md)' }],
        'display-lg':  ['var(--type-size-display-lg)',  { lineHeight: 'var(--type-lh-display-lg)' }],
      },
      fontFamily: {
        sans: ['Roboto', 'sans-serif'],
      },
      boxShadow: {
        'xs': 'var(--shadow-xs)',
        'sm': 'var(--shadow-sm)',
        'md': 'var(--shadow-md)',
        'lg': 'var(--shadow-lg)',
        'xl': 'var(--shadow-xl)',
      },
    },
  },
  plugins: [],
}
